### ISSUE TITLE
"Bad Token"

### ISSUE THREAD

**Issue by sakarki** [mnxn/TI84CE-Binary#1]
Tried opening/sending "Binary.8xp" program in the TI Connect CE, and leaves me with error message "Bad Token!". 
Photo: https://imgur.com/VHXdpey

**Comment by mnxn** [comment]
Sending the app works on the 5.4 version of the OS and TI Connect Software for me.

I just read this: https://education.ti.com/en/software/update/84-ce-software-update/84ce-download
> we’ve made the decision to remove ASM functionality in our latest OS update to prioritize learning and minimize security risks

Unfortunately, it seems that TI has removed support for `ASM` in later versions of the OS, which this program requires. Jailbreaking your OS with [arTIfiCE](https://yvantt.github.io/arTIfiCE/) may be an option, but I personally haven't tried it, so use at your own risk. 

I'm sorry for any inconvenience.

**Comment by sakarki** [comment]
No worries, great job on the code nonetheless and ty for responding promptly! :)

**Comment by sakarki** [comment]
I got it to work on my calculator since i didn't update to the new OS. The TI Connect wasn't letting me send the program by selecting the file, however dragging it into my connected calculator worked. Thank you for the update info and alternatives, learned a a lot about the OS and to make sure I don't upgrade it in the future.

**Comment by mnxn** [comment]
That's good to hear! Glad you got it working.
